{% include "header.phtml" %}
    </ul>
<ul class="operator">
    {% if isBatchDeleteBut %}<li id="batchdelbut"><span><img src="{{static_url('assets')}}/images/t03.png" /></span>批量删除</li>{% endif %}
    <li><span><img src="{{static_url('assets')}}/images/t04.png" /></span><a href="{{url('comment/list')}}{{cond}}">刷新</a></li>
</ul>
</div>
<div class="rightinfo">
    <div class="tools">
        <form action="{{url('comment/list')}}" method="post">
            <ul class="search">
                <li><label for="isshow">显示状态</label><b>:</b>
                    <select id="isshow" name="isshow">
                        <option value="-1">全部</option>
                        {% for index,name in shows %}
                            <option value="{{index}}" {% if index == isshow %} selected="selected" {% endif %}>{{name}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><label for="istop">是否置顶</label><b>:</b>
                    <select id="istop" name="istop">
                        <option value="-1">全部</option>
                        {% for index,name in tops %}
                        <option value="{{index}}" {% if index == istop %} selected="selected" {% endif %}>{{name}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><input type="hidden" name="navid" value="{{navId}}"/><input type="submit" value="搜索" class="search-but"/></li>
            </ul>
        </form>
    </div>
    <table class="tablelist">
        <thead>
        <tr>
            <th><input name="" type="checkbox" value="" class="checkbut"/></th>
            <th>序号</th>
            <th>ID</th>
            <th>文章标题</th>
            <th>评论内容</th>
            <th>评论人</th>
            <th>是否置顶</th>
            <th>是否显示</th>
            <th>评论时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for index,comment in comments %}
        <tr>
            <td><input name="id"  class="checkinput" type="checkbox" value="{{comment['id']}}" /></td>
            <td>{{index+1}}</td>
            <td>{{comment['id']}}</td>
            <td>{{comment['title']}}</td>
            <td><a href="{{url('/comment/profile')}}/id/{{comment['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">查看</a></td>
            <td>{{comment['creator']}}</td>
            <td>{{comment['topname']}}</td>
            <td>{{comment['showname']}}</td>
            <td>{{comment['createtime']}}</td>
            <td>
                {% if isSetBut %}
                {% if defaultShow == comment['isshow']%}
                <a href="{{url('/comment/hide')}}/id/{{comment['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">隐藏</a>|
                {% else %}
                <a href="{{url('/comment/show')}}/id/{{comment['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">显示</a>|
                {% endif %}
                {% if defaultTop == comment['istop']%}
                <a href="{{url('/comment/cancel')}}/id/{{comment['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">取消置顶</a>|
                {% else %}
                <a href="{{url('/comment/top')}}/id/{{comment['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">置顶</a>|
                {% endif %}
                {% endif %}
                <a href="{{url('/reply/list')}}/commentid/{{comment['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">回复管理</a>|
                {% if isDeleteBut %}<a href="{{url('/comment/delete')}}/id/{{comment['id']}}{{cond}}" class="tablelink">删除</a>{% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagin">
        {% if page['num'] %}
        <div class="message">共<i class="blue">{{page['total']}}</i>条记录，当前显示第&nbsp;<i class="blue">{{page['page']}}&nbsp;</i>页</div>
        <ul class="paginList">
            <li class="paginItem"><a href="{{url('/comment/list/page/')}}{{page['before']}}{{cond}}"><span class="pagepre"></span></a></li>
            {% for index in 1..page['num'] %}
            {% if page['page'] == index %}
            <li class="paginItem current"><a href="{{url('/comment/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% else %}
            <li class="paginItem"><a href="{{url('/comment/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% endif %}
            {% endfor %}
            <li class="paginItem"><a href="{{url('/comment/list/page/')}}{{page['next']}}{{cond}}"><span class="pagenxt"></span></a></li>
        </ul>
        {% else %}
        <p align="center">暂无记录...</p>
        {% endif %}
    </div>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkbut').click(function(){
            $('.checkinput').attr("checked",$(this).is(':checked'));
        });
        $('#batchdelbut').click(function(){
            var ids = '';

            $(".checkinput:checked").each(function(i, n){
                ids += $(this).val() + ',';
            });

            if(!ids){
                alert('请先选择需要删除的评论!');
            }else{
                location.href = '/comment/delete/{{cond}}/id/' + ids;
            }
        })
    });
    $('.tablelist tbody tr:odd').addClass('odd');
</script>
{% include "footer.phtml" %}