{% include "header.phtml" %}
<li><a href="{{url('black/edit')}}/id/{{black['id']}}{{cond}}">编辑黑名单</a></li>
</ul>
</div>
<div class="formbody">
    <form action="{{url('black/save')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li>
                <label for="type">禁用功能</label>
                <select name="type" id="type">
                    {% for index,name in types %}
                    <option value="{{index}}" {% if index == black['type'] %}selected="selected"{% endif %}>{{name}}</option>
                    {% endfor %}
                </select>
                {% for index,econd in conds %}
                <input type="hidden" name="{{index}}" value="{{econd}}"/>
                {% endfor %}
            </li>
            <li><label for="uid">用户ID</label><input id="uid" name="uid" value="{{black['uid']}}" type="text" class="dfinput" /></li>
            <li><label for="cause">原因</label><textarea id="cause" name="cause" class="dfinput" style="height: 150px;resize: none;">{{black['cause']}}</textarea></li>
            <li><label>&nbsp;</label><input type="hidden" name="id" value="{{black['id']}}"/><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var uid = document.getElementById('uid');
        if('' == uid.value){
            alert('用户ID必填!');
            return false;
        }
        return true;
    }
</script>
{% include "footer.phtml" %}