{% include "header.phtml" %}
</ul>
<ul class="operator">
    {% if isCreateBut %}<li><span><img src="{{static_url('assets')}}/images/t01.png" /></span><a href="{{url('black/create')}}{{cond}}">添加黑名单</a></li>{% endif %}
    {% if isBatchDeleteBut %}<li id="batchdelbut"><span><img src="{{static_url('assets')}}/images/t03.png" /></span>批量删除</li>{% endif %}
    <li><span><img src="{{static_url('assets')}}/images/t04.png" /></span><a href="{{url('black/list')}}{{cond}}">刷新</a></li>
</ul>
</div>
<div class="rightinfo">
    <div class="tools">
        <form action="{{url('black/list')}}" method="post">
            <ul class="search">
                <li><label for="username">用户名</label><b>:</b><input type="text" value="{{userName}}" name="username" id="username"/></li>
                <li><label for="type">禁用功能</label><b>:</b>
                    <select id="type" name="type">
                        <option value="-1">全部</option>
                        {% for index,typeName in types %}
                        <option value="{{index}}" {% if index == type %}selected="selected"{% endif %}>{{typeName}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><input type="hidden" name="navid" value="{{navId}}"/><input type="submit" value="搜索" class="search-but"/></li>
            </ul>
        </form>
    </div>
    <table class="tablelist">
        <thead>
        <tr>
            <th><input name="" type="checkbox" value="" class="checkbut"/></th>
            <th>序号</th>
            <th>ID</th>
            <th>用户ID</th>
            <th>用户名</th>
            <th>禁用功能</th>
            <th>原因</th>
            <th>添加者</th>
            <th>添加时间</th>
            <th>最后操作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for index,black in blacks %}
        <tr>
            <td><input name="blackid"  class="checkinput" type="checkbox" value="{{black['id']}}" /></td>
            <td>{{index+1}}</td>
            <td>{{black['id']}}</td>
            <td>{{black['uid']}}</td>
            <td>{{black['username']}}</td>
            <td>{{black['typename']}}</td>
            <td>{{black['cause']}}</td>
            <td>{{black['creator']}}</td>
            <td>{{black['createtime']}}</td>
            <td>{{black['lastoperator']}}</td>
            <td>
                {% if isUpdateBut %}<a href="{{url('/black/edit')}}/id/{{black['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">编辑</a>|{% endif %}
                {% if isDeleteBut %}<a href="{{url('/black/delete')}}/id/{{black['id']}}{{cond}}" class="tablelink">删除</a>{% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagin">
        {% if page['num'] %}
        <div class="message">共<i class="blue">{{page['total']}}</i>条记录，当前显示第&nbsp;<i class="blue">{{page['page']}}&nbsp;</i>页</div>
        <ul class="paginList">
            <li class="paginItem"><a href="{{url('/black/list/page/')}}{{page['before']}}{{cond}}"><span class="pagepre"></span></a></li>
            {% for index in 1..page['num'] %}
            {% if page['page'] == index %}
            <li class="paginItem current"><a href="{{url('/black/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% else %}
            <li class="paginItem"><a href="{{url('/black/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% endif %}
            {% endfor %}
            <li class="paginItem"><a href="{{url('/black/list/page/')}}{{page['next']}}{{cond}}"><span class="pagenxt"></span></a></li>
        </ul>
        {% else %}
        <p align="center">暂无记录...</p>
        {% endif %}
    </div>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkbut').click(function(){
            $('.checkinput').attr("checked",$(this).is(':checked'));
        });
        $('#batchdelbut').click(function(){
            var ids = '';

            $(".checkinput:checked").each(function(i, n){
                ids += $(this).val() + ',';
            });

            if(!ids){
                alert('请先选择需要删除的黑名单信息!');
            }else{
                location.href = '/black/delete/{{cond}}/id/' + ids;
            }
        })
    });
    $('.tablelist tbody tr:odd').addClass('odd');
</script>
{% include "footer.phtml" %}