{% include "header.phtml" %}
<li><a href="{{url('link/create')}}{{cond}}">添加友情链接</a></li>
</ul>
</div>
<div class="formbody">
    <form action="{{url('link/post')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li><label for="name">链接名称</label><input id="name" name="name" value="" type="text" class="dfinput" /></li>
            <li><label for="url">链接地址</label><input id="url" name="url" value="" type="text" class="dfinput" /></li>
            <li>
                <label for="enabled">是否启用</label>
                <select name="enabled" id="enabled">
                    {% for index,name in enableds %}
                    <option value="{{index}}" {% if index == defaultEnabled %}selected="selected"{% endif %}>{{name}}</option>
                    {% endfor %}
                </select>
            </li>
            <li><label for="displayorder">排序值</label><input id="displayorder" name="displayorder" value="255" type="text" class="dfinput" /></li>
            <li><label>&nbsp;</label><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var name = document.getElementById('name');
        var url = document.getElementById('url');

        if('' == name.value){
            alert('友情链接名称必填!');
            return false;
        }
        if('' == url.value){
            alert('友情链接地址必填!');
            return false;
        }
        return true;
    }
</script>
{% include "footer.phtml" %}