{% include "header.phtml" %}
<li><a href="{{url('category/create')}}{{cond}}">添加分类信息</a></li>
</ul>
</div>
<div class="formbody">
    <form action="{{url('category/post')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li>
                <label for="parentid">分类归属</label>
                <select name="parentid" id="parentid">
                    <option value="0">顶级分类</option>
                    {% for category in categorys %}
                    <option value="{{category['id']}}">{{category['name']}}{{category['name_extra']}}</option>
                    {% endfor %}
                </select>
            </li>
            <li>
                <label for="type">分类类型</label>
                <select name="type" id="type">
                    <option value="0">普通类型</option>
                    <option value="1">下载类型</option>
                    <option value="2">作品类型</option>
                    <option value="3">其他类型</option>
                </select>
            </li>
            <li>
                <label for="enabled">是否启用</label>
                <select name="enabled" id="enabled">
                    {% for index,name in enableds %}
                    <option value="{{index}}" {% if index == enabled %}selected="selected"{% endif %}>{{name}}</option>
                    {% endfor %}
                </select>
            </li>
            <li><label for="name">分类名称</label><input id="name" name="name" value="" type="text" class="dfinput" /></li>
            <li><label for="displayorder">排序值</label><input id="displayorder" name="displayorder" value="255" type="text" class="dfinput" /></li>
            <li><label>&nbsp;</label><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var name = document.getElementById('name');

        if('' == name.value){
            alert('分类名称必填!');
            return false;
        }

        return true;
    }
</script>
{% include "footer.phtml" %}