{% include "header.phtml" %}
        <li><a href="{{url('menu/create')}}{{cond}}">添加菜单</a></li>
    </ul>
</div>
<div class="formbody">
    <form action="{{url('menu/post')}}{{cond}}" method="post">
    <ul class="forminfo">
        <li>
            <label for="parentid">菜单归属</label>
            <select name="parentid" id="parentid">
                <option value="0">顶级菜单</option>
                {% for topMenu in topMenus %}
                    <option value="{{topMenu['id']}}">{{topMenu['name']}}</option>
                {% endfor %}
            </select>
        </li>
        <li>
            <label for="type">菜单类型</label>
            <select name="type" id="type">
                {% for index,name in types %}
                    <option value="{{index}}">{{name}}</option>
                {% endfor %}
            </select>
        </li>
        <li><label for="name">菜单名称</label><input id="name" name="name" value="" type="text" class="dfinput" /></li>
        <li><label for="code">菜单code</label><input id="code" name="code" value="" type="text" class="dfinput" /></li>
        <li><label>是否有子菜单</label><cite><input name="haschild" type="radio" value="1"/>&nbsp;是&nbsp;&nbsp;&nbsp;&nbsp;<input name="haschild" type="radio" value="0" checked="checked"/>&nbsp;否</cite></li>
        <li><label>是否启用</label><cite><input name="enabled" type="radio" value="1" checked="checked" />&nbsp;是&nbsp;&nbsp;&nbsp;&nbsp;<input name="enabled" type="radio" value="0" />&nbsp;否</cite></li>
        <li><label for="url">菜单地址</label><input id="url" name="url" type="text" class="dfinput" value="http://www.yuyinet.cn" /></li>
        <li><label for="displayorder">排序值</label><input id="displayorder" name="displayorder" type="text" class="dfinput" value="255" /></li>
        <li><label for="auth">权限配置</label><input id="auth" name="auth" type="text" class="dfinput" value="" placeholder='例: {"blog.menu.top":"L"}'/></li>
        <li><label>&nbsp;</label><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
    </ul>
    </form>
</div>
<script type="text/javascript">
    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var name = document.getElementById('name');
        var code = document.getElementById('code');

        if('' == name.value){
            alert('菜单名称必填!');
            return false;
        }

        if('' == code.value){
            alert('菜单code必填!');
            return false;
        }

        return true;
    }
</script>
{% include "footer.phtml" %}