{% include "header.phtml" %}
<li><a href="{{url('reply/list')}}{{cond}}">回复管理</a></li>
        <li><a href="{{url('reply/create')}}{{cond}}">回复评论</a></li>
    </ul>
</div>
<div class="formbody">
    <form action="{{url('reply/post')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li><label id="name">评论人</label><input type="text" class="dfinput" name="name" id="name" value="{{name}}" disabled="disabled"></li>
            <li><label for="comment">评论内容</label><textarea class="dfinput" style="resize: none;height: 180px;" disabled="disabled">{{content}}</textarea></li>
            <li><label for="content">回复内容</label><textarea class="dfinput" id="content" name="content" style="resize: none;height: 180px;"></textarea></li>
            <li><label>&nbsp;</label><input type="hidden" name="commentid" value="{{id}}"/><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var content = document.getElementById('content');
        if('' == content.value){
            alert('回复内容必填!');
            return false;
        }
        return true;
    }
</script>
{% include "footer.phtml" %}