{% include "header.phtml" %}
<li><a href="{{url('photo/list')}}{{cond}}">相片管理</a> {% if albumName %}({{albumName}}){% endif %}</li>
<li><a href="{{url('photo/create')}}{{cond}}">添加相片</a></li>
</ul>
</div>
<div class="formbody">
    <form action="{{url('photo/post')}}{{cond}}" method="post" enctype="multipart/form-data">
        <ul class="forminfo">
            <li><label for="name">相片名称</label><input id="name" name="_name" value="" type="text" class="dfinput" /></li>
            <li><label for="photo">上传相片</label><input type="file" name="photo" id="photo" class="dfinput"/></li>
            <li><label for="description">描述</label></li>
            <li style="padding-left: 85px;"><script type="text/plain" id="myEditor"></script></li>
            <li><label>&nbsp;</label><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript" src="{{static_url('assets')}}/ueditor/third-party/jquery.min.js"></script>
<script type="text/javascript" charset="utf-8" src="{{static_url('assets')}}/ueditor/umeditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="{{static_url('assets')}}/ueditor/umeditor.min.js"></script>
<script type="text/javascript" src="{{static_url('assets')}}/ueditor/lang/zh-cn/zh-cn.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var um = UM.getEditor('myEditor',{
            toolbar:[
                'source | undo redo | bold italic underline strikethrough | forecolor backcolor',
                'fontfamily fontsize' ,
                'link unlink',
                '| fullscreen'
            ],
            zIndex: 0,
            initialFrameHeight: 200,
            initialFrameWidth: 345
        });
    });

    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var name = document.getElementById('name');

        if('' == name.value){
            alert('相片名称必填!');
            return false;
        }

        return true;
    }
</script>
{% include "footer.phtml" %}