{% include "header.phtml" %}
        <li><a href="{{url('tag/create')}}{{cond}}">添加标签</a></li>
    </ul>
</div>
<div class="formbody">
    <form action="{{url('tag/post')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li><label for="name">标签名称</label><input id="name" name="name" value="" type="text" class="dfinput" /></li>
            <li>
            <label for="enabled">是否启用</label>
                <select name="enabled" id="enabled">
                {% for index,name in enableds %}
                    <option value="{{index}}" {% if index == defaultEnabled %}selected="selected"{% endif %}>{{name}}</option>
                {% endfor %}
                </select>
            </li>
            <li><label>&nbsp;</label><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var name = document.getElementById('name');

        if('' == name.value){
            alert('标签名称必填!');
            return false;
        }

        return true;
    }
</script>
{% include "footer.phtml" %}