{% include "header.phtml" %}
<li><a href="{{url('home/msg')}}{{cond}}">发消息</a></li>
</ul>
</div>
<div class="formbody">
    <form action="{{url('home/sendmsg')}}{{cond}}" method="post" id="myform">
        <ul class="forminfo">
            <li><label for="typeid">消息类型</label><select id="typeid" name="typeid">
                    <option value="0">默认类别</option>
                    {% for msgType in msgTypes %}
                    <option value="{{msgType['id']}}">{{msgType['name']}}</option>
                    {% endfor %}
            </select></li>
            <li><label for="poster">接收对象</label><select id="poster" name="poster">
                    <option value="0">所有用户</option>
                    <option value="1">网站用户</option>
                    <option value="2">后台用户</option>
                </select></li>
            <li><label for="title">消息标题</label><input id="title" name="title" value="" type="text" class="dfinput" /></li>
            <li><label for="content">消息内容</label></li>
            <li style="padding-left: 85px;"><script type="text/plain" id="myEditor"></script></li>
            <li><label>&nbsp;</label><input name="" type="submit" id="btn" class="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript" charset="utf-8" src="{{static_url('assets')}}/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="{{static_url('assets')}}/ueditor/ueditor.all.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var um = UE.getEditor('myEditor',{
            toolbars: [
                ['fullscreen', 'undo', 'redo', 'bold','italic', 'underline', 'fontborder', 'strikethrough', 'emotion', 'simpleupload', 'insertcode'],
                ['justifyleft', 'justifyright', 'justifycenter','justifyjustify', 'removeformat', 'formatmatch', 'pasteplain', '|', 'forecolor', 'backcolor', 'insertorderedlist', 'insertunorderedlist', 'cleardoc']
            ],
            zIndex: 0,
            initialFrameHeight: 200,
            initialFrameWidth: 345,
            wordCount:false,
            elementPathEnabled : false,
            serverUrl: '{{uploadUrl}}'
        });

        $('#myform').submit(function(){
            if(!$('#title').val()){
                alert('消息标题不能为空!');

                return false;
            }
            if(!$('#myEditor').text()){
                alert('消息内容不能为空!');

                return false;
            }
            return true;
        });
    });
</script>
{% include "footer.phtml" %}