{% include "header.phtml" %}
</ul>
</div>
<div class="formbody">
    <form action="{{url('home/setpassword')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li><label for="username">用户名称</label><input id="username" name="username" value="{{user['username']}}" type="text" disabled="disabled" class="dfinput" /></li>
            <li><label for="password">新密码</label><input id="password" name="password" value="" type="password" class="dfinput" /></li>
            <li><label for="repassword">确认密码</label><input id="repassword" name="repassword" value="" type="password" class="dfinput" /></li>
            <li><label>&nbsp;</label><input type="hidden" name="id" value="{{user['id']}}"><input name="" type="submit" class="btn" id="btn" value="确认保存" {% if !isPasswdBut %}  title='禁止操作' style='background-image:none;background-color:#ddd; cursor:not-allowed;' disabled='disabled' {% endif %}/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var password = document.getElementById('password');
        var repassword = document.getElementById('repassword');

        if('' == password.value){
            alert('密码必填!');
            return false;
        }

        if(password.value != repassword.value){
            alert('两次密码填写不一致!');
            return false;
        }

        return true;
    }
</script>
{% include "footer.phtml" %}