{% include "header.phtml" %}
<li><a href="{{url('notice/create')}}{{cond}}">添加公告信息</a></li>
</ul>
</div>
<div class="formbody">
    <form action="{{url('notice/post')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li><label for="title">公告标题</label><input id="title" name="title" value="" type="text" class="dfinput" /></li>
            <li>
                <label for="status">公告状态</label>
                <select name="status" id="status">
                    {% for index,name in status %}
                    <option value="{{index}}">{{name}}</option>
                    {% endfor %}
                </select>
            </li>
            <li><label for="content">公告内容</label></li>
            <li style="padding-left: 85px;"><script type="text/plain" id="myEditor"></script></li>
            <li><label>&nbsp;</label><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript" src="{{static_url('assets')}}/ueditor/third-party/jquery.min.js"></script>
<script type="text/javascript" charset="utf-8" src="{{static_url('assets')}}/ueditor/umeditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="{{static_url('assets')}}/ueditor/umeditor.min.js"></script>
<script type="text/javascript" src="{{static_url('assets')}}/ueditor/lang/zh-cn/zh-cn.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var um = UM.getEditor('myEditor',{
            toolbar:[
                'source | undo redo | bold italic underline strikethrough | forecolor backcolor',
                'fontfamily fontsize' ,
                'link unlink | emotion image',
                '| fullscreen'
            ],
            zIndex: 0,
            initialFrameHeight: 200,
            initialFrameWidth: 345,
            imageUrl:'{{uploadUrl}}'
        });
    });
    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var title = document.getElementById('title');
        if('' == title.value){
            alert('公告标题必填!');
            return false;
        }
        return true;
    }
</script>
{% include "footer.phtml" %}