{% include "header.phtml" %}
<li><a href="{{url('notice/edit')}}/id/{{notice['id']}}{{cond}}">编辑公告</a></li>
</ul>
</div>
<div class="formbody">
    <form action="{{url('notice/save')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li><label for="title">公告标题</label><input id="title" name="title" value="{{notice['title']}}" type="text" class="dfinput" /></li>
            <li><label for="sendname">发布人</label><input id="sendname" name="sendname" value="{{notice['sendname']}}" disabled="disabled" type="text" class="dfinput" /></li>
            <li>
                <label for="status">公告状态</label>
                <select name="status" id="status">
                    {% for index,name in status %}
                    <option value="{{index}}" {% if index == notice['status'] %}selected="selected"{% endif %}>{{name}}</option>
                    {% endfor %}
                </select>
                {% for index,econd in conds %}
                <input type="hidden" name="{{index}}" value="{{econd}}"/>
                {% endfor %}
            </li>
            <li><label for="content">公告内容</label></li>
            <li style="padding-left: 85px;" class="clearspan"><script type="text/plain" id="myEditor">{{notice['content']}}</script></li>
            <li><label>&nbsp;</label><input type="hidden" name="id" value="{{notice['id']}}"/><input name="" type="submit" class="btn" id="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript" charset="utf-8" src="{{static_url('assets')}}/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="{{static_url('assets')}}/ueditor/ueditor.all.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var um = UE.getEditor('myEditor',{
            toolbars:[
                ['fullscreen', 'undo', 'redo', 'bold','italic', 'underline', 'fontborder', 'strikethrough', 'emotion', 'simpleupload', 'insertcode'],
                ['justifyleft', 'justifyright', 'justifycenter','justifyjustify', 'removeformat', 'formatmatch', 'pasteplain', '|', 'forecolor', 'backcolor', 'insertorderedlist', 'insertunorderedlist', 'cleardoc']
            ],
            zIndex: 0,
            initialFrameHeight: 200,
            initialFrameWidth: 345,
            wordCount:false,
            elementPathEnabled : false,
            serverUrl:'{{uploadUrl}}'
        });
    });

    var btn = document.getElementById('btn');
    btn.onclick = function(){
        var title = document.getElementById('title');

        if('' == title.value){
            alert('公告标题必填!');
            return false;
        }
        return true;
    }
</script>
{% include "footer.phtml" %}