{% include "header.phtml" %}
</ul>
<ul class="operator">
    {% if isCreateBut %}<li><span><img src="{{static_url('assets')}}/images/t01.png" /></span><a href="{{url('notice/create')}}{{cond}}">添加公告</a></li>{% endif %}
    {% if isBatchDeleteBut %}<li id="batchdelbut"><span><img src="{{static_url('assets')}}/images/t03.png" /></span>批量删除</li>{% endif %}
    <li><span><img src="{{static_url('assets')}}/images/t04.png" /></span><a href="{{url('notice/list')}}{{cond}}">刷新</a></li>
</ul>
</div>
<div class="rightinfo">
    <div class="tools">
        <form action="{{url('notice/list')}}" method="post">
            <ul class="search">
                <li><label for="title">标题</label><b>:</b><input type="text" value="{{title}}" name="title" id="title"/></li>
                <li><label for="sendname">发布人</label><b>:</b><input type="text" value="{{sendName}}" name="sendname" id="sendname"/></li>
                <li><label for="status">公告状态</label><b>:</b>
                    <select id="status" name="status">
                        <option value="-1">全部</option>
                        {% for index,name in status %}
                        <option value="{{index}}" {% if index == statu %}selected="selected"{% endif %}>{{name}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><input type="hidden" name="navid" value="{{navId}}"/><input type="submit" value="搜索" class="search-but"/></li>
            </ul>
        </form>
    </div>
    <table class="tablelist">
        <thead>
        <tr>
            <th><input name="" type="checkbox" value="" class="checkbut"/></th>
            <th>序号</th>
            <th>ID</th>
            <th>标题</th>
            <th>发布人</th>
            <th>显示时间</th>
            <th>状态</th>
            <th>添加者</th>
            <th>添加时间</th>
            <th>最后操作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for index,notice in notices %}
        <tr>
            <td><input name="id"  class="checkinput" type="checkbox" value="{{notice['id']}}" /></td>
            <td>{{index+1}}</td>
            <td>{{notice['id']}}</td>
            <td>{{notice['title']}}</td>
            <td>{{notice['sendname']}}</td>
            <td>{{notice['showtime']}}</td>
            <td>{{notice['statusname']}}</td>
            <td>{{notice['creator']}}</td>
            <td>{{notice['createtime']}}</td>
            <td>{{notice['lastoperator']}}</td>
            <td>
                {% if isUpdateBut or (loginName == notice['sendname'])%}<a href="{{url('/notice/edit')}}/id/{{notice['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">编辑</a>{% endif %}
                {% if isDeleteBut and (delStatus != notice['status']) %}|<a href="{{url('/notice/delete')}}/id/{{notice['id']}}{{cond}}" class="tablelink">删除</a>{% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagin">
        {% if page['num'] %}
        <div class="message">共<i class="blue">{{page['total']}}</i>条记录，当前显示第&nbsp;<i class="blue">{{page['page']}}&nbsp;</i>页</div>
        <ul class="paginList">
            <li class="paginItem"><a href="{{url('/notice/list/page/')}}{{page['before']}}{{cond}}"><span class="pagepre"></span></a></li>
            {% for index in 1..page['num'] %}
            {% if page['page'] == index %}
            <li class="paginItem current"><a href="{{url('/notice/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% else %}
            <li class="paginItem"><a href="{{url('/notice/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% endif %}
            {% endfor %}
            <li class="paginItem"><a href="{{url('/notice/list/page/')}}{{page['next']}}{{cond}}"><span class="pagenxt"></span></a></li>
        </ul>
        {% else %}
        <p align="center">暂无记录...</p>
        {% endif %}
    </div>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkbut').click(function(){
            $('.checkinput').attr("checked",$(this).is(':checked'));
        });
        $('#batchdelbut').click(function(){
            var ids = '';

            $(".checkinput:checked").each(function(i, n){
                ids += $(this).val() + ',';
            });

            if(!ids){
                alert('请先选择需要删除的公告信息!');
            }else{
                location.href = '/notice/delete/{{cond}}/id/' + ids;
            }
        })
    });
    $('.tablelist tbody tr:odd').addClass('odd');
</script>
{% include "footer.phtml" %}