{% include "header.phtml" %}
        <li><a href="{{url('role/edit')}}/id/{{role['id']}}{{cond}}">编辑角色</a></li>
    </ul>
</div>
<div class="formbody">
    <form action="{{url('role/save')}}{{cond}}" method="post">
        <ul class="forminfo">
            <li>
                <label for="type">角色类型</label>
                <select name="type" id="type">
                    {% for index,name in roleTypes %}
                    <option value="{{index}}" {% if index == role['type'] %}selected='selected'{% endif %}>{{name}}</option>
                    {% endfor %}
                </select>
                {% for index,econd in conds %}
                <input type="hidden" name="{{index}}" value="{{econd}}"/>
                {% endfor %}
            </li>
            <li><label for="name">角色名称</label><input id="name" name="name" value="{{role['name']}}" type="text" class="dfinput" /></li>
            <li><label for="code">角色code</label><input id="code" name="code" value="{{role['code']}}" type="text" class="dfinput" /></li>
            <li><label>是否启用</label><cite>{% for index,roleEnable in roleEnables %}<input name="enabled" type="radio" value="{{index}}" {% if role['enabled'] == index %}checked="checked"{% endif %}/>&nbsp;{{roleEnable}}&nbsp;&nbsp;&nbsp;&nbsp;{% endfor %}</cite></li>
            <li><label for="displayorder">排序值</label><input id="displayorder" name="displayorder" type="text" class="dfinput" value="{{role['displayorder']}}" /></li>
            <li><label for="description">角色描述</label><textarea name="description" class="dfinput" style="resize: none;height: 100px;">{{role['description']}}</textarea></li>
            <li><label>&nbsp;</label><input type="hidden" name="id" value="{{role['id']}}"/><input name="" type="submit" id="btn" class="btn" value="确认保存"/><input style="margin-left: 68px;" name="" type="reset" class="btn" value="重置信息"/></li>
        </ul>
    </form>
</div>
{% include "footer.phtml" %}