{% include "header.phtml" %}
    </ul>
<ul class="operator">
    {% if isCreateBut %}<li><span><img src="{{static_url('assets')}}/images/t01.png" /></span><a href="{{url('role/create')}}{{cond}}">添加角色</a></li>{% endif %}
    {% if isBatchDeleteBut %}<li id="batchdelbut"><span><img src="{{static_url('assets')}}/images/t03.png" /></span>批量删除</li>{% endif %}
    <li><span><img src="{{static_url('assets')}}/images/t04.png" /></span><a href="{{url('role/list')}}{{cond}}">刷新</a></li>
</ul>
</div>
<div class="rightinfo">
    <div class="tools">
        <form action="{{url('/role/list')}}" method="post">
            <ul class="search">
                <li><label for="name">名称</label><b>:</b><input type="text" value="{{name}}" name="name" id="name"/></li>
                <li><label for="code">code</label><b>:</b><input type="text" value="{{code}}" name="code" id="code"/></li>
                <li><label for="type">类型</label><b>:</b>
                    <select id="type" name="type">
                    <option value="-1">全部类型</option>
                    {% for index,roleType in roleTypes %}
                        <option value="{{index}}" {% if index == type%}selected="selected"{% endif %}>{{roleType}}</option>
                    {% endfor %}
                    </select>
                </li>
                <li><label for="enabled">是否启用</label><b>:</b>
                    <select id="enabled" name="enabled">
                        <option value="-1">全部</option>
                        {% for index,roleEnable in roleEnables%}
                            <option value="{{index}}" {% if index == enabled %}selected="selected"{% endif %}>{{roleEnable}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><input type="hidden" name="navid" value="{{navId}}"><input type="submit" value="搜索" class="search-but"/></li>
            </ul>
        </form>
    </div>
    <table class="tablelist">
        <thead>
        <tr>
            <th><input name="" type="checkbox" value="" class="checkbut"/></th>
            <th>序号</th>
            <th>ID</th>
            <th>名称</th>
            <th>code</th>
            <th>类型</th>
            <th>是否启用</th>
            <th>排序值</th>
            <th>添加者</th>
            <th>添加时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for index,role in roles %}
        <tr>
            <td><input name="menuid"  class="checkinput" type="checkbox" value="{{role['id']}}" /></td>
            <td>{{index + 1}}</td>
            <td>{{role['id']}}</td>
            <td >{{role['name']}}</td>
            <td>{{role['code']}}</td>
            <td>{{role['typename']}}</td>
            <td>{{role['enablename']}}</td>
            <td>{{role['displayorder']}}</td>
            <td>{{role['creator']}}</td>
            <td>{% if role['createtime'] %}{{date('Y-m-d H:i:s', role['createtime'])}}{% endif %}</td>
            <td>
                <a href="{{url('/role/auth')}}/id/{{role['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">权限项</a>|
                {% if isUpdateBut %}<a href="{{url('/role/edit')}}/id/{{role['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">编辑</a>|{% endif %}
                {% if isDeleteBut %}<a href="{{url('/role/delete/id/')}}{{role['id']}}{{cond}}" class="tablelink">删除</a>{% endif %}
                {% if isSetBut %}|
                {% if role['enabled'] %}
                <a href="{{url('/role/disabled')}}/id/{{role['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">禁用</a>
                {% else %}
                <a href="{{url('/role/enabled')}}/id/{{role['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">启用</a>
                {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagin">
        {% if page['num'] %}
        <div class="message">共<i class="blue">{{page['total']}}</i>条记录，当前显示第&nbsp;<i class="blue">{{page['page']}}&nbsp;</i>页</div>
        <ul class="paginList">
            <li class="paginItem"><a href="{{url('/role/list/page/')}}{{page['before']}}{{cond}}"><span class="pagepre"></span></a></li>
            {% for index in 1..page['num'] %}
            {% if page['page'] == index %}
            <li class="paginItem current"><a href="{{url('/role/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% else %}
            <li class="paginItem"><a href="{{url('/role/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% endif %}
            {% endfor %}
            <li class="paginItem"><a href="{{url('/role/list/page/')}}{{page['next']}}{{cond}}"><span class="pagenxt"></span></a></li>
        </ul>
        {% else %}
        <p align="center">暂无记录...</p>
        {% endif %}
    </div>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkbut').click(function(){
            $('.checkinput').attr("checked",$(this).is(':checked'));
        });

        $('#batchdelbut').click(function(){
            var ids = '';

            $(".checkinput:checked").each(function(i, n){
                ids += $(this).val() + ',';
            });

            if(!ids){
                alert('请先选择需要删除的角色!');
            }else{
                location.href = '/role/delete/{{cond}}/id/' + ids;
            }
        })
    });

    $('.tablelist tbody tr:odd').addClass('odd');
</script>
{% include "footer.phtml" %}