<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>禹译后台管理系统</title>
    <link href="{{static_url('assets')}}/css/style.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
    <script language="javascript">
        $(function(){
            $('.error').css({'position':'absolute','left':($(window).width()-490)/2});
            $(window).resize(function(){
                $('.error').css({'position':'absolute','left':($(window).width()-490)/2});
            })
        });
    </script>
</head>
<body style="background:#edf6fa;">
<div class="error">
    <h1>操作失败</h1>
    <h2>{{msg}}</h2>
    <p><span id="timer">{{timer}}</span>秒后自动跳转...</p>
    <div class="reindex"><a href="{{url}}" {% if url == "/" %} target="_parent" {% endif %}>立即跳转</a></div>
</div>
<script type="text/javascript">
    window.onload = function () {
        var timerObj = document.getElementById('timer');
        var timer = null;
        var url = '{{url}}';

        timer = setInterval(function () {
            var sec = parseInt(timerObj.innerHTML);
            sec -= 1;
            if (sec > 0) {
                timerObj.innerHTML = sec;
            }else{
                clearInterval(timer);
                {% if url == "/" %}
                    parent.location.href = url;
                {% else %}
                    window.location.href = url;
                {% endif %}
            }
        }, 1000);
    }
</script>
</body>
</html>