{% include "header.phtml" %}
    </ul>
<ul class="operator">
    {% if isCreateBut %}<li><span><img src="{{static_url('assets')}}/images/t01.png" /></span><a href="{{url('album/create')}}{{cond}}">添加相册</a></li>{% endif %}
    {% if isBatchDeleteBut %}<li id="batchdelbut"><span><img src="{{static_url('assets')}}/images/t03.png" /></span>批量删除</li>{% endif %}
    <li><span><img src="{{static_url('assets')}}/images/t04.png" /></span><a href="{{url('album/list')}}{{cond}}">刷新</a></li>
</ul>
</div>
<div class="rightinfo">
    <div class="tools">
        <form action="{{url('album/list')}}" method="post">
            <ul class="search">
                <li><label for="name">相册名</label><b>:</b><input type="text" value="{{name}}" name="name" id="name"/></li>
                <li><label for="enabled">是否启用</label><b>:</b>
                    <select id="enabled" name="enabled">
                        <option value="-1">全部</option>
                        {% for index,name in enableds %}
                            <option value="{{index}}" {% if index == enabled %} selected="selected" {% endif %}>{{name}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><input type="hidden" name="navid" value="{{navId}}"/><input type="submit" value="搜索" class="search-but"/></li>
            </ul>
        </form>
    </div>
    <table class="tablelist">
        <thead>
        <tr>
            <th><input name="" type="checkbox" value="" class="checkbut"/></th>
            <th>序号</th>
            <th>ID</th>
            <th>名称</th>
            <th>封面</th>
            <th>相片数量</th>
            <th>是否启用</th>
            <th>排序值</th>
            <th>添加者</th>
            <th>添加时间</th>
            <th>最后操作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for index,album in albums %}
        <tr>
            <td><input name="id"  class="checkinput" type="checkbox" value="{{album['id']}}" /></td>
            <td>{{index+1}}</td>
            <td>{{album['id']}}</td>
            <td>{{album['name']}}</td>
            <td>{% if album['cover'] %}<img src="{{album['cover']}}" height="50"/>{% endif %}</td>
            <td>{{album['photos']}}</td>
            <td>{{album['enabledname']}}</td>
            <td>{{album['displayorder']}}</td>
            <td>{{album['creator']}}</td>
            <td>{{album['createtime']}}</td>
            <td>{{album['lastoperator']}}</td>
            <td>
                {% if isUpdateBut %}<a href="{{url('/album/edit')}}/id/{{album['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">编辑</a>|{% endif %}
                <a href="{{url('/photo/list')}}/albumid/{{album['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">相片管理</a>
                {% if isSetBut %}|
                {% if defaultEnabled == album['enabled'] %}
                <a href="{{url('/album/disabled')}}/id/{{album['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">禁用</a>
                {% else %}
                <a href="{{url('/album/enabled')}}/id/{{album['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">启用</a>
                {% endif %}
                {% endif %}
                {% if isDeleteBut %}|<a href="{{url('/album/delete')}}/id/{{album['id']}}{{cond}}" class="tablelink">删除</a>
                {% endif %}
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagin">
        {% if page['num'] %}
        <div class="message">共<i class="blue">{{page['total']}}</i>条记录，当前显示第&nbsp;<i class="blue">{{page['page']}}&nbsp;</i>页</div>
        <ul class="paginList">
            <li class="paginItem"><a href="{{url('/album/list/page/')}}{{page['before']}}{{cond}}"><span class="pagepre"></span></a></li>
            {% for index in 1..page['num'] %}
            {% if page['page'] == index %}
            <li class="paginItem current"><a href="{{url('/album/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% else %}
            <li class="paginItem"><a href="{{url('/album/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% endif %}
            {% endfor %}
            <li class="paginItem"><a href="{{url('/album/list/page/')}}{{page['next']}}{{cond}}"><span class="pagenxt"></span></a></li>
        </ul>
        {% else %}
        <p align="center">暂无记录...</p>
        {% endif %}
    </div>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkbut').click(function(){
            $('.checkinput').attr("checked",$(this).is(':checked'));
        });
        $('#batchdelbut').click(function(){
            var ids = '';

            $(".checkinput:checked").each(function(i, n){
                ids += $(this).val() + ',';
            });

            if(!ids){
                alert('请先选择需要删除的相册!');
            }else{
                location.href = '/album/delete/{{cond}}/id/' + ids;
            }
        })
    });
    $('.tablelist tbody tr:odd').addClass('odd');
</script>
{% include "footer.phtml" %}