{% include "header.phtml" %}
        <li><a href="{{url('sonauthitem/list')}}/parentid/{{parentId}}{{curcond}}">子权限项</a>({{topAuthName}})</li>
    </ul>
<ul class="operator">
    {% if isBatchDeleteBut %}<li id="batchdelbut"><span><img src="{{static_url('assets')}}/images/t03.png" /></span>批量删除</li>{% endif %}
    <li><span><img src="{{static_url('assets')}}/images/t04.png" /></span><a href="{{url('sonauthitem/list')}}/parentid/{{parentId}}{{curcond}}">刷新</a></li>
</ul>
</div>
<div class="rightinfo">
    <div class="tools">
        <form action="{{url('/sonauthitem/list')}}/parentid/{{parentId}}" method="post">
            <ul class="search">
                <li><label for="name">名称</label><b>:</b><input type="text" value="{{name}}" name="name" id="name"/></li>
                <li><label for="code">code</label><b>:</b><input type="text" value="{{code}}" name="code" id="code"/></li>
                <li><label for="type">类型</label><b>:</b>
                    <select id="type" name="type">
                        <option value="-1">全部</option>
                        {% for index,typeName in types %}
                        <option value="{{index}}" {% if type == index %}selected="selected"{% endif %}>{{typeName}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><label for="enabled">是否启用</label><b>:</b>
                    <select id="enabled" name="enabled">
                        <option value="-1">全部</option>
                        {% for index,authItemEnable in authItemEnables %}
                        <option value="{{index}}" {% if enabled == index %}selected="selected"{% endif %}>{{authItemEnable}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><input type="hidden" name="navid" value="{{navId}}"/><input type="submit" value="搜索" class="search-but"/></li>
            </ul>
        </form>
    </div>
    <table class="tablelist">
        <thead>
        <tr>
            <th><input name="" type="checkbox" value="" class="checkbut"/></th>
            <th>序号</th>
            <th>ID</th>
            <th>名称</th>
            <th>code</th>
            <th>类型</th>
            <th>是否启用</th>
            <th>排序值</th>
            <th>原子项</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for index,authItem in authItems %}
        <tr>
            <td><input class="checkinput" type="checkbox" value="{{authItem['id']}}" /></td>
            <td>{{index + 1}}</td>
            <td>{{authItem['id']}}</td>
            <td >{{authItem['name']}}</td>
            <td>{{authItem['code']}}</td>
            <td>{{authItem['typename']}}</td>
            <td>{{authItem['enablename']}}</td>
            <td>{{authItem['displayorder']}}</td>
            <td>{{authItem['auth']}}</td>
            <td>
                {% if isUpdateBut %}<a href="{{url('/sonauthitem/edit')}}/parentid/{{parentId}}/id/{{authItem['id']}}/page/{{page['page']}}{{curcond}}" class="tablelink">编辑</a>|{% endif %}
                {% if isDeleteBut %}<a href="{{url('/sonauthitem/delete/')}}parentid/{{parentId}}/id/{{authItem['id']}}{{curcond}}" class="tablelink">删除</a>|{% endif %}
                {% if isSetBut %}
                {% if authItem['enabled'] %}
                <a href="{{url('/sonauthitem/disabled')}}/parentid/{{parentId}}/id/{{authItem['id']}}/page/{{page['page']}}{{curcond}}" class="tablelink">禁用</a>
                {% else %}
                <a href="{{url('/sonauthitem/enabled')}}/parentid/{{parentId}}/id/{{authItem['id']}}/page/{{page['page']}}{{curcond}}" class="tablelink">启用</a>
                {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagin">
        {% if page['num'] %}
        <div class="message">共<i class="blue">{{page['total']}}</i>条记录，当前显示第&nbsp;<i class="blue">{{page['page']}}&nbsp;</i>页</div>
        <ul class="paginList">
            <li class="paginItem"><a href="{{url('/sonauthitem/list/')}}parentid/{{parentId}}/page/{{page['before']}}{{curcond}}"><span class="pagepre"></span></a></li>
            {% for index in 1..page['num'] %}
            {% if page['page'] == index %}
            <li class="paginItem current"><a href="{{url('/sonauthitem/list/')}}parentid/{{parentId}}/page/{{index}}{{curcond}}">{{index}}</a></li>
            {% else %}
            <li class="paginItem"><a href="{{url('/sonauthitem/list/')}}parentid/{{parentId}}/page/{{index}}{{curcond}}">{{index}}</a></li>
            {% endif %}
            {% endfor %}
            <li class="paginItem"><a href="{{url('/sonauthitem/list/')}}parentid/{{parentId}}/page/{{page['next']}}{{curcond}}"><span class="pagenxt"></span></a></li>
        </ul>
        {% else %}
        <p align="center">暂无记录...</p>
        {% endif %}
    </div>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkbut').click(function(){
            $('.checkinput').attr("checked",$(this).is(':checked'));
        });

        $('#batchdelbut').click(function(){
            var ids = '';

            $(".checkinput:checked").each(function(i, n){
                ids += $(this).val() + ',';
            });

            if(!ids){
                alert('请先选择需要删除的权限项!');
            }else{
                location.href = '/sonauthitem/delete/parentid/{{parentId}}{{curcond}}/id/' + ids;
            }
        })
    });

    $('.tablelist tbody tr:odd').addClass('odd');
</script>
{% include "footer.phtml" %}