{% include "header.phtml" %}
<li><a href="{{url('soncategory/list')}}/parentid/{{parentId}}{{curcond}}">子分类</a></li>
</ul>
<ul class="operator">
    {% if isBatchDeleteBut %}<li id="batchdelbut"><span><img src="{{static_url('assets')}}/images/t03.png" /></span>批量删除</li>{% endif %}
    <li><span><img src="{{static_url('assets')}}/images/t04.png" /></span><a href="{{url('soncategory/list')}}/parentid/{{parentId}}{{curcond}}">刷新</a></li>
</ul>
</div>
<div class="rightinfo">
    <div class="tools">
        <form action="{{url('soncategory/list')}}/parentid/{{parentId}}" method="post">
            <ul class="search">
                <li><label for="name">分类名</label><b>:</b><input type="text" value="{{name}}" name="name" id="name"/></li>
                <li><label for="enabled">是否启用</label><b>:</b>
                    <select id="enabled" name="enabled">
                        <option value="-1">全部</option>
                        {% for index,name in enableds %}
                        <option value="{{index}}" {% if index == enabled %} selected="selected" {% endif %}>{{name}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><input type="hidden" name="navid" value="{{navId}}"/><input type="submit" value="搜索" class="search-but"/></li>
            </ul>
        </form>
    </div>
    <table class="tablelist">
        <thead>
        <tr>
            <th><input name="" type="checkbox" value="" class="checkbut"/></th>
            <th>序号</th>
            <th>ID</th>
            <th>父分类名</th>
            <th>名称</th>
            <th>是否启用</th>
            <th>排序值</th>
            <th>添加者</th>
            <th>添加时间</th>
            <th>最后操作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for index,category in categorys %}
        <tr>
            <td><input name="id"  class="checkinput" type="checkbox" value="{{category['id']}}" /></td>
            <td>{{index+1}}</td>
            <td>{{category['id']}}</td>
            <td>{{topCategoryName}}</td>
            <td>{{category['name']}}</td>
            <td>{{category['enabledname']}}</td>
            <td>{{category['displayorder']}}</td>
            <td>{{category['creator']}}</td>
            <td>{{category['createtime']}}</td>
            <td>{{category['lastoperator']}}</td>
            <td>
                {% if isUpdateBut %}<a href="{{url('/soncategory/edit')}}/parentid/{{parentId}}/id/{{category['id']}}/page/{{page['page']}}{{curcond}}" class="tablelink">编辑</a>|{% endif %}
                {% if isSetBut %}
                {% if defaultEnabled == category['enabled'] %}
                <a href="{{url('/soncategory/disabled')}}/parentid/{{parentId}}/id/{{category['id']}}/page/{{page['page']}}{{curcond}}" class="tablelink">禁用</a>
                {% else %}
                <a href="{{url('/soncategory/enabled')}}/parentid/{{parentId}}/id/{{category['id']}}/page/{{page['page']}}{{curcond}}" class="tablelink">启用</a>
                {% endif %}
                {% endif %}
                {% if isDeleteBut %}|<a href="{{url('/soncategory/delete')}}/parentid/{{parentId}}/id/{{category['id']}}{{curcond}}" class="tablelink">删除</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagin">
        {% if page['num'] %}
        <div class="message">共<i class="blue">{{page['total']}}</i>条记录，当前显示第&nbsp;<i class="blue">{{page['page']}}&nbsp;</i>页</div>
        <ul class="paginList">
            <li class="paginItem"><a href="{{url('/soncategory/list/page/')}}{{page['before']}}/parentid/{{parentId}}{{curcond}}"><span class="pagepre"></span></a></li>
            {% for index in 1..page['num'] %}
            {% if page['page'] == index %}
            <li class="paginItem current"><a href="{{url('/soncategory/list/page/')}}{{index}}/parentid/{{parentId}}{{curcond}}">{{index}}</a></li>
            {% else %}
            <li class="paginItem"><a href="{{url('/soncategory/list/page/')}}{{index}}/parentid/{{parentId}}{{curcond}}">{{index}}</a></li>
            {% endif %}
            {% endfor %}
            <li class="paginItem"><a href="{{url('/soncategory/list/page/')}}{{page['next']}}/parentid/{{parentId}}{{curcond}}"><span class="pagenxt"></span></a></li>
        </ul>
        {% else %}
        <p align="center">暂无记录...</p>
        {% endif %}
    </div>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkbut').click(function(){
            $('.checkinput').attr("checked",$(this).is(':checked'));
        });
        $('#batchdelbut').click(function(){
            var ids = '';

            $(".checkinput:checked").each(function(i, n){
                ids += $(this).val() + ',';
            });

            if(!ids){
                alert('请先选择需要删除的分类信息!');
            }else{
                location.href = '/soncategory/delete/parentid/{{parentId}}/{{curcond}}/id/' + ids;
            }
        })
    });
    $('.tablelist tbody tr:odd').addClass('odd');
</script>
{% include "footer.phtml" %}