<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>禹译后台管理系统</title>
    <link href="{{static_url('assets')}}/css/style.css" rel="stylesheet" type="text/css" />
    <link href="{{static_url('assets')}}/ueditor/themes/default/css/umeditor.css" type="text/css" rel="stylesheet">
</head>
<body>
<div class="place">
    <span>位置：</span>
    <ul class="placeul">
        <li><a href="{{url('/')}}" target="_parent">首页</a></li>
        <li>{% if navTopMenu %}{{navTopMenu['name']}}{% else %}幽灵菜单{% endif %}</li>
        {% if navSonMenu %}
        <li><a href="{{navSonMenu['url']}}{{cond}}">{{navSonMenu['name']}}</a></li>
        {% else %}
        <li>幽灵菜单</a></li>
        {% endif %}