{% include "header.phtml" %}
</ul>
<ul class="operator">
    {% if isCreateBut %}<li><span><img src="{{static_url('assets')}}/images/t01.png" /></span><a href="{{url('advert/create')}}{{cond}}">添加广告</a></li>{% endif %}
    {% if isBatchDeleteBut %}<li id="batchdelbut"><span><img src="{{static_url('assets')}}/images/t03.png" /></span>批量删除</li>{% endif %}
    <li><span><img src="{{static_url('assets')}}/images/t04.png" /></span><a href="{{url('advert/list')}}{{cond}}">刷新</a></li>
</ul>
</div>
<div class="rightinfo">
    <div class="tools">
        <form action="{{url('advert/list')}}" method="post">
            <ul class="search">
                <li><label for="name">广告名称</label><b>:</b><input type="text" value="{{name}}" name="name" id="name"/></li>
                <li><label for="status">广告状态</label><b>:</b>
                    <select id="status" name="status">
                        <option value="-1">全部</option>
                        {% for index,name in status %}
                        <option value="{{index}}" {% if index == statu %}selected="selected"{% endif %}>{{name}}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><input type="hidden" name="navid" value="{{navId}}"/><input type="submit" value="搜索" class="search-but"/></li>
            </ul>
        </form>
    </div>
    <table class="tablelist">
        <thead>
        <tr>
            <th><input name="" type="checkbox" value="" class="checkbut"/></th>
            <th>序号</th>
            <th>ID</th>
            <th>名称</th>
            <th>位置</th>
            <th>价位</th>
            <th>类型</th>
            <th>开始时间</th>
            <th>结束时间</th>
            <th>状态</th>
            <th>添加者</th>
            <th>添加时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for index,advert in adverts %}
        <tr>
            <td><input name="id"  class="checkinput" type="checkbox" value="{{advert['id']}}" /></td>
            <td>{{index+1}}</td>
            <td>{{advert['id']}}</td>
            <td>{{advert['name']}}</td>
            <td>{{advert['spot']}}</td>
            <td>{{advert['price']}}元</td>
            <td>{{advert['pricetype']}}</td>
            <td>{{advert['starttime']}}</td>
            <td>{{advert['endtime']}}</td>
            <td>{{advert['statusname']}}</td>
            <td>{{advert['creator']}}</td>
            <td>{{advert['createtime']}}</td>
            <td>
                {% if isUpdateBut %}<a href="{{url('/advert/edit')}}/id/{{advert['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">编辑</a>|{% endif %}
                {% if isDeleteBut %}<a href="{{url('/advert/delete')}}/id/{{advert['id']}}{{cond}}" class="tablelink">删除</a>{% endif %}
                {% if (isSetBut and (disabled != advert['status'])) %}|<a href="{{url('/advert/disabled')}}/id/{{advert['id']}}/page/{{page['page']}}{{cond}}" class="tablelink">关闭</a>{% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagin">
        {% if page['num'] %}
        <div class="message">共<i class="blue">{{page['total']}}</i>条记录，当前显示第&nbsp;<i class="blue">{{page['page']}}&nbsp;</i>页</div>
        <ul class="paginList">
            <li class="paginItem"><a href="{{url('/advert/list/page/')}}{{page['before']}}{{cond}}"><span class="pagepre"></span></a></li>
            {% for index in 1..page['num'] %}
            {% if page['page'] == index %}
            <li class="paginItem current"><a href="{{url('/advert/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% else %}
            <li class="paginItem"><a href="{{url('/advert/list/page/')}}{{index}}{{cond}}">{{index}}</a></li>
            {% endif %}
            {% endfor %}
            <li class="paginItem"><a href="{{url('/advert/list/page/')}}{{page['next']}}{{cond}}"><span class="pagenxt"></span></a></li>
        </ul>
        {% else %}
        <p align="center">暂无记录...</p>
        {% endif %}
    </div>
</div>
<script type="text/javascript" src="{{static_url('assets')}}/js/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkbut').click(function(){
            $('.checkinput').attr("checked",$(this).is(':checked'));
        });
        $('#batchdelbut').click(function(){
            var ids = '';

            $(".checkinput:checked").each(function(i, n){
                ids += $(this).val() + ',';
            });

            if(!ids){
                alert('请先选择需要删除的广告信息!');
            }else{
                location.href = '/advert/delete/{{cond}}/id/' + ids;
            }
        })
    });
    $('.tablelist tbody tr:odd').addClass('odd');
</script>
{% include "footer.phtml" %}